---
fluentbit_arch: "win64"
fluentbit_install_method: "zip"
fluentbit_install_dir: "C:\\Program Files\\fluent-bit"
fluentbit_download_dir: "C:\\temp"
fluentbit_download_url: "https://packages.fluentbit.io/windows/fluent-bit-{{ fluentbit_version }}-{{ fluentbit_arch }}.zip"
fluentbit_conf_dir: "{{ fluentbit_install_dir }}\\conf"
fluentbit_bin_dir: "{{ fluentbit_install_dir }}\\bin"
fluentbit_db_directory: "C:\\ProgramData\\fluent-bit\\db"
fluentbit_storage_directory: "C:\\ProgramData\\fluent-bit\\storage"
fluentbit_config_file: "{{ fluentbit_conf_dir }}\\fluent-bit.yml"
fluentbit_parsers_path: "{{ fluentbit_conf_dir }}\\parsers.yml"
fluentbit_parsers_include: "parsers.yml"
fluentbit_service_name: "fluent-bit"
fluentbit_service_display_name: "Fluent Bit"
fluentbit_service_description: "Fluent Bit log collector service"
fluentbit_service_startup_type: "auto"
fluentbit_service_state: "started"
fluentbit_win_firewall_rule_profiles: "domain,private,public"
fluentbit_win_firewall_rule_remoteip: "any"
fluentbit_win_firewall_rule_state: "present"
