---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: f9n.general.fluentbit
      vars:
        fluentbit_pipelines:
          - inputs: |
              - name: dummy
                tag: test
                dummy: '{"message": "oflu"}'
            outputs: |
              - name: stdout
                match: "*"
