---
- name: Restart Fluent Bit
  ansible.builtin.systemd:
    name: "{{ fluentbit_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_os_family != 'Windows'
  become: true

- name: Restart Fluent Bit
  ansible.windows.win_service:
    name: "{{ fluentbit_service_name }}"
    state: restarted
  when: ansible_os_family == 'Windows'
